modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="camman_but_blocks_are_big"
version="1.0.0"
displayName="Camman But Blocks Are Big"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="feder, MCreator"

[[dependencies.camman_but_blocks_are_big]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




