modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="camman_but_blocks_are_big"
version="1.0.0"
displayName="Camman But Blocks Are Big"
credits="The_WereF0X, Camman18"
displayURL="https://discord.gg/zGjRZWeSdw"
updateJSONURL="https://discord.gg/zGjRZWeSdw"
authors="The_WereF0X"
description="Adds Big Blocks from Camman18's video Minecraft but blocks are bigger"

[[dependencies.camman_but_blocks_are_big]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




